# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos/uploadVideo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio_sample.mp3"
Content-Type: audio/mpeg

// o arquivo precisa estar no mesmo diretório do routes.http
< ./audio_sample.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/e24cc19b-4e62-43b6-9cbf-6a20fdb75972/transcription
Content-Type: application/json

{
  "prompt": "pix, my instants, asssovio"
}


###

# @name generate-ai-completion
POST http://localhost:3333/ai/generate
Content-Type: application/json

{
  "videoId": "e24cc19b-4e62-43b6-9cbf-6a20fdb75972",
  "temperature": 0,
  "prompt": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}